/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ListBusinessRouteImport } from './routes/list-business'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as AddBusinessRouteImport } from './routes/add-business'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BusinessIdRouteImport } from './routes/business.$id'

const ListBusinessRoute = ListBusinessRouteImport.update({
  id: '/list-business',
  path: '/list-business',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const AddBusinessRoute = AddBusinessRouteImport.update({
  id: '/add-business',
  path: '/add-business',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIdRoute = BusinessIdRouteImport.update({
  id: '/business/$id',
  path: '/business/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-business': typeof AddBusinessRoute
  '/businesses': typeof BusinessesRoute
  '/list-business': typeof ListBusinessRoute
  '/business/$id': typeof BusinessIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-business': typeof AddBusinessRoute
  '/businesses': typeof BusinessesRoute
  '/list-business': typeof ListBusinessRoute
  '/business/$id': typeof BusinessIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-business': typeof AddBusinessRoute
  '/businesses': typeof BusinessesRoute
  '/list-business': typeof ListBusinessRoute
  '/business/$id': typeof BusinessIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-business'
    | '/businesses'
    | '/list-business'
    | '/business/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-business' | '/businesses' | '/list-business' | '/business/$id'
  id:
    | '__root__'
    | '/'
    | '/add-business'
    | '/businesses'
    | '/list-business'
    | '/business/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddBusinessRoute: typeof AddBusinessRoute
  BusinessesRoute: typeof BusinessesRoute
  ListBusinessRoute: typeof ListBusinessRoute
  BusinessIdRoute: typeof BusinessIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/list-business': {
      id: '/list-business'
      path: '/list-business'
      fullPath: '/list-business'
      preLoaderRoute: typeof ListBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-business': {
      id: '/add-business'
      path: '/add-business'
      fullPath: '/add-business'
      preLoaderRoute: typeof AddBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/$id': {
      id: '/business/$id'
      path: '/business/$id'
      fullPath: '/business/$id'
      preLoaderRoute: typeof BusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddBusinessRoute: AddBusinessRoute,
  BusinessesRoute: BusinessesRoute,
  ListBusinessRoute: ListBusinessRoute,
  BusinessIdRoute: BusinessIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
